name: Publish Docker image to DockerHub container registry

# Executes every time something is pushed to the main branch
# which in this case is the 'master'
on:
  push:
    branches: [ main ]    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB_USR }}
          password: ${{ secrets.DOCKER_HUB_KEY }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build & Push
        run: |
          docker build . --file Dockerfile --tag ${{ secrets.DOCKER_HUB_USR }}/docker-cicd:latest
          docker push ${{ secrets.DOCKER_HUB_USR }}/docker-cicd:latest 
