name: Publish Docker image to GitHub container registry

# Executes every time something is pushed to the main branch
# which in this case is the 'master'
on:
  push:
    branches: [ main ]    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: List checked out files
        run: ls -la
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_HUB_CR_KEY }}
          registry: ghcr.io
          repository: henningbertsch/docker-cicd
          tags: latest
          dockerfile: Dockerfile